name: "Generate Ubuntu 22.04 leap images"

on:
  workflow_dispatch:
      inputs:
        version:
          description: 'Value=<maj.min.patch> (e.e. if leap tag is v4.0.4, value should be "4.0.4")'
          required: true

jobs:
  leap-dependencies-image:
    name: Dependencies image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'AntelopeIO/leap'
          ref: v${{ github.event.inputs.version }}
          submodules: false
          fetch-depth: 0

      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMAGE="${REGISTRY}/${{ github.repository_owner }}/leap-dependencies-ubuntu-2204"
          TAGS="${IMAGE}:${{ github.sha }},${IMAGE}:${{ github.event.inputs.version }}"
          echo "tags=${TAGS,,}" >> $GITHUB_ENV

      - name: Showtag
        id: showtag
        run: echo "${{ github.env.tags }}"

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: .cicd/platforms/ubuntu22.Dockerfile
          tags: ${{ steps.prep.outputs.tags }}

  leap-image:
    needs: leap-dependencies-image
    name: Leap image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMAGE="${REGISTRY}/${{ github.repository_owner }}/leap-dependencies-ubuntu-2204"
          TAGS="${IMAGE}:${{ github.sha }},${IMAGE}:${{ github.event.inputs.version }}"
          echo "tags=${TAGS,,}" >> $GITHUB_ENV

      - name: Showtag
        id: showtag
        run: echo "${{ github.env.tags }}"

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            LEAP_VER=${{ github.event.inputs.version }}
          file: docker/ubuntu_2204-leap.Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
